In [1]:
from src.preprocessing import parse_data, split_train_test
from src.training import trainer
from src.models import LSTM, LSTMAtt, CNN
from src.evaluation import eval_model
import torch

# Load data

In [2]:
df, labels = parse_data()

In [3]:
df_train_features, df_train_labels, df_val_features, df_val_labels = split_train_test(df, labels)

In [4]:
print(df_train_features.shape, df_train_labels.shape, df_val_features.shape, df_val_labels.shape)

torch.Size([34, 24, 1]) torch.Size([34]) torch.Size([33, 24, 1]) torch.Size([33])


In [5]:
import torch
torch.unique(labels, return_counts=True)

(tensor([0, 1]), tensor([33, 34]))

In [6]:
torch.unique(df_train_labels, return_counts=True)

(tensor([0, 1]), tensor([13, 21]))

In [7]:
torch.unique(df_val_labels , return_counts=True)

(tensor([0, 1]), tensor([20, 13]))

# Training

In [8]:
n_epochs = 500
tolerance = 100
freq_print = 10

In [9]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"

### LSTM

In [10]:
lstm_model = LSTM(1, 10, 1, 2)

In [11]:
device

'cuda:0'

In [12]:
lstm_model = trainer(
    model=lstm_model,
    n_epochs=n_epochs,
    X_train=df_train_features,
    y_train=df_train_labels,
    X_val=df_val_features,
    y_val=df_val_labels,
    device=device,
    tolerance=tolerance,
    freq_print=freq_print,
)

Epoch = 9, 	Loss = 0.6971585750579834, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 19, 	Loss = 0.6420931816101074, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 29, 	Loss = 0.6616765260696411, 	Training_acc = 0.6794871794871795, 	Validation_acc = 0.6692307692307693
Epoch = 39, 	Loss = 0.6047766208648682, 	Training_acc = 0.6355311355311355, 	Validation_acc = 0.6596153846153847
Epoch = 49, 	Loss = 0.6538292765617371, 	Training_acc = 0.6355311355311355, 	Validation_acc = 0.6730769230769231
Epoch = 59, 	Loss = 0.6251329183578491, 	Training_acc = 0.6355311355311355, 	Validation_acc = 0.6730769230769231
Epoch = 69, 	Loss = 0.6258093118667603, 	Training_acc = 0.6355311355311355, 	Validation_acc = 0.6730769230769231
Epoch = 79, 	Loss = 0.6107276678085327, 	Training_acc = 0.6355311355311355, 	Validation_acc = 0.698076923076923
Epoch = 89, 	Loss = 0.5515342354774475, 	Training_acc = 0.6593406593406593, 	Validation_acc = 0.698076923076923
Epoch = 99, 	Loss = 0.5565928220748901, 	Train

### LSTMAtt

In [13]:
lstmatt_model = LSTMAtt(1, 30, 1, 2)

In [14]:
lstmatt_model = trainer(
    model=lstmatt_model,
    n_epochs=n_epochs,
    X_train=df_train_features,
    y_train=df_train_labels,
    X_val=df_val_features,
    y_val=df_val_labels,
    device=device,
    tolerance=tolerance,
    freq_print=freq_print,
)

Epoch = 9, 	Loss = 0.6064983010292053, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 19, 	Loss = 0.6150121092796326, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 29, 	Loss = 0.5709090232849121, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 39, 	Loss = 0.5085048079490662, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 49, 	Loss = 0.5515789985656738, 	Training_acc = 0.47985347985347987, 	Validation_acc = 0.47692307692307695
Epoch = 59, 	Loss = 0.5328212380409241, 	Training_acc = 0.47985347985347987, 	Validation_acc = 0.47692307692307695
Epoch = 69, 	Loss = 0.48128336668014526, 	Training_acc = 0.4560439560439561, 	Validation_acc = 0.47692307692307695
Epoch = 79, 	Loss = 0.4628163278102875, 	Training_acc = 0.5183150183150182, 	Validation_acc = 0.47692307692307695
Epoch = 89, 	Loss = 0.493915319442749, 	Training_acc = 0.5421245421245421, 	Validation_acc = 0.6038461538461539
Epoch = 99, 	Loss = 0.4514884352684021, 	Training_acc = 0.6043956043956045, 	Validation_acc = 0.66

### CNN

In [15]:
df_train_features_cnn = df_train_features.transpose(1, 2)
df_val_features_cnn = df_val_features.transpose(1, 2)

In [16]:
cnn_model = CNN(2)

In [17]:
cnn_model = trainer(
    model=cnn_model,
    n_epochs=n_epochs,
    X_train=df_train_features_cnn,
    y_train=df_train_labels,
    X_val=df_val_features_cnn,
    y_val=df_val_labels,
    device=device,
    tolerance=tolerance,
    freq_print=freq_print,
)

Epoch = 9, 	Loss = 0.682962954044342, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 19, 	Loss = 0.6293696165084839, 	Training_acc = 0.5, 	Validation_acc = 0.5
Epoch = 29, 	Loss = 0.49825331568717957, 	Training_acc = 0.5714285714285714, 	Validation_acc = 0.5
Epoch = 39, 	Loss = 0.504095196723938, 	Training_acc = 0.8095238095238095, 	Validation_acc = 0.8461538461538461
Epoch = 49, 	Loss = 0.6003747582435608, 	Training_acc = 0.9523809523809523, 	Validation_acc = 0.9230769230769231
Epoch = 59, 	Loss = 0.5780887007713318, 	Training_acc = 0.9761904761904762, 	Validation_acc = 0.9615384615384616
Epoch = 69, 	Loss = 0.4853639006614685, 	Training_acc = 0.9761904761904762, 	Validation_acc = 0.9615384615384616
Epoch = 79, 	Loss = 0.45815330743789673, 	Training_acc = 0.9761904761904762, 	Validation_acc = 0.9615384615384616
Epoch = 89, 	Loss = 0.48641467094421387, 	Training_acc = 0.9761904761904762, 	Validation_acc = 0.9615384615384616
Epoch = 99, 	Loss = 0.41935408115386963, 	Training_acc = 0

# Evaluation

In [18]:
df_test, labels_test = parse_data(data_path='./data/ItalyPowerDemand_TEST.ts')

In [19]:
_ = eval_model(model_name="LSTM", model=lstm_model, X_test=df_test, y_test=labels_test, device=device)

LSTM test accuracy = 0.8232977469513577


In [20]:
_ = eval_model(model_name="LSTM with Attention", model=lstmatt_model, X_test=df_test, y_test=labels_test, device=device)

LSTM with Attention test accuracy = 0.7731991477401514


In [21]:
df_test_cnn = df_test.transpose(1, 2)
_ = eval_model(model_name="CNN", model=cnn_model, X_test=df_test_cnn, y_test=labels_test, device=device)

CNN test accuracy = 0.8898862142436194


# Saliency